name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development
    tags: 
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run the tests (optional)
      # - name: Run the tests
      #   run: npm run test

      # Step 5: Build the project
      - name: Build
        run: npm run build
        
  docker-build-push:
      runs-on: ubuntu-latest
      needs: ["build"]
      if: startsWith(github.ref, 'refs/tags/')
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build Docker image
          run: |
            docker build -t "${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:${GITHUB_REF_NAME}" .
          shell: bash
        - name: Push Docker images
          run: |
            docker push "${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:${GITHUB_REF_NAME}"
          shell: bash

        